version: '3'
services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: roulette
    volumes:
      - mysql-data:/var/lib/mysql
    ports: 
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  dealer:
    image: roulette/dealer:latest
    restart: always
    build:
      context: .
      args:
        PROJECT_PATH: ./roulette.dealer
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
    depends_on:
      - rabbitmq
    ports:
      - 8080:8080

  monitor:
    image: roulete/monitor:latest
    restart: always
    build:
      context: .
      args:
        PROJECT_PATH: ./roulette.monitor
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - 8081:8080

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  rabbitmq_exporter:
    image: kbudde/rabbitmq-exporter
    depends_on:
      - "rabbitmq"
    ports:
      - 9999:9419
    environment:
      RABBIT_URL: "http://rabbitmq:15672"
      PUBLISH_PORT: "9419"
      OUTPUT_FORMAT: "JSON"

  grafana:
    image: grafana/grafana
    restart: always
    volumes: 
      - grafana-data:/var/lib/grafana
      - ./dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning/
    ports:
      - 3000:3000

volumes:
  prometheus-data:
  grafana-data:
  mysql-data: