# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: dealer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['dealer:8080']
  - job_name: monitor
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['monitor:8080']
  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq_exporter:9419']